### ISSUE TITLE
Debug.log not working

### ISSUE THREAD

**Issue by Norlock** [marc136/snowpack-plugin-elm#11]
Hi Marc,

Thanks for the plugin, the Debug.log "", is neither showing in console or in the snowpack output. I followed this guide: https://dev.to/mickeyvip/creating-an-elm-project-with-snowpack-1c1b

Example output:

    case result of
        Ok markers ->
            { model | markers = markers }

        Err err ->
            let
                _ =
                    Debug.log (Debug.toString err)
            in
            { model | error = Just errorMsg }

**Comment by marc136** [comment]
Hello @Norlock,

great that you're trying out elm and this plugin.

The Debug.log function expects two parameters, the first is a string, and the second is an arbitrary value. See https://package.elm-lang.org/packages/elm/core/latest/Debug#log 

This code should print what you want to the js console:
```elm
case result of
    Ok markers ->
        { model | markers = markers }

    Err err ->
        let
            _ =
                Debug.log "Result was not ok" err
        in
        { model | error = Just errorMsg }
```

Cheers, Marc

**Comment by Norlock** [comment]
Sorry, yes that works. I for some reason thought it was like this and the compiler didn't complain.

**Comment by marc136** [comment]
The compiler does not complain,  because to him, you just declared a function `_ : a -> a` and don't call it.

**Comment by Norlock** [comment]
Ah strange, I thought first one between () should return string so it should complain. But I can see it be like that, learned something new today.
