### ISSUE TITLE
Option to disable debug mode in dev

### ISSUE THREAD

**Issue by UnwrittenFun** [marc136/snowpack-plugin-elm#2]
It would be great to have an option to disable the elm debugger as for the app i'm currently making, it gets quite in the way. I would prefer to be able to enable it as and when i need it. 

![image](https://user-images.githubusercontent.com/3743418/97572515-4707e300-19e0-11eb-88f2-1e2d0da603c0.png)

Thanks for the plugin!

**Comment by marc136** [comment]
Hello @UnwrittenFun, you can can now disable the elm debugger like this:

In snowpack.config.json
```json
"plugins": [
  [
    "../../../elm-plugin.js",
    { "verbose": false, "debugger": "never", "optimize": "build" }
  ]
],
```
