### ISSUE TITLE
Need to restart Snowpack when there is a compilation error

### ISSUE THREAD

**Issue by mickeyvip** [marc136/snowpack-plugin-elm#4]
When there is a compilation error, the nice error dialog is presented.

But when the error is fixed there are several things that seem not right:

* the error dialog is still shown
* saving new changes seem to send a new module to the browser, but the HTML is not updated
* I can close the error dialog, but the HTML is not updated after the error is fixed
* refreshing the browser looks like it's stuck on loading (in the tab title) and in the "Network" tab I see that the fetching of my Elm app is the one that is "pending"

The only thing that worked for me is restarting the app.

Thank you.

**Comment by marc136** [comment]
Thank you @mickeyvip for this bug report.

There was a very stupid error I introduced when ensuring that `elm make` runs only once at a time, that now no longer exists. 

After the change in d4b275d, I was no longer able to reproduce the issue, and the error in the browser when running `snowpack dev` now is now removed on HMR.

Cheers,
marc

**Comment by mickeyvip** [comment]
Hi @marc136,

Thank you for the quick response!

Version `0.4.2` works correctly.
