### ISSUE TITLE
example HMR not working

### ISSUE THREAD

**Issue by okkdev** [marc136/snowpack-plugin-elm#5]
I don't know if I'm doing something wrong.

After doing `yarn install && cd example/ && yarn install && yarn start` and changing something in an elm file doesn't hot reload the changes. 👀

**Comment by marc136** [comment]
Hi @okkdev,

can you give me more information?
Is it possible that you are using a Snowpack version prior to 2.14.0? HMR for `Indirect.elm` needs at least v2.14.0.

I tried to reproduce your steps, but on my Linux machine HMR was triggered when I changed `example/Sandbox1.elm`, `example/Indirect.elm` or `example/index.js`.

Do you also get output like this when navigating to the elm app? Or is something missing?

```sh
$ npx yarn start
yarn run v1.22.10
warning package.json: No license field
$ snowpack dev
[snowpack] Nothing to install.
  http://localhost:8080
  Server started in 43ms.


[elm-plugin] aquiring lock to compile src/Sandbox1.elm
[elm-plugin] aquired lock to compile src/Sandbox1.elm
[elm-plugin] load { file: 'src/Sandbox1.elm', isDev: true, isHmrEnabled: true }
[elm-plugin] src/Sandbox1.elm imports [
  'src/Indirect.elm',
  'src/Nested/Hello.elm',
  'src/Nested/Number8.elm'
]
```

I used `npx yarn <cmd>` instead, but I don't think that should change anything.

It generated the following lockfile. Maybe you can spot a difference.
[yarn.lock.zip](https://github.com/marc136/snowpack-plugin-elm/files/5705625/yarn.lock.zip)

**Comment by okkdev** [comment]
Thanks, for some reason it works now. I have no clue what happened last time, I even pulled the repo multiple times to make sure I didn't accidentally change anything.
